# Generated by Django 4.0 on 2022-08-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audify', '0002_artist_genre_song_playlist_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='upload',
            field=models.ImageField(upload_to='media/artists/<django.db.models.fields.CharField>/%D'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='upload',
            field=models.ImageField(blank=True, upload_to='media/playlists/<django.db.models.query_utils.DeferredAttribute object at 0x0000023372B0B3A0>/% Y/% m/% d/'),
        ),
    ]
