# Generated by Django 4.0 on 2022-08-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audify', '0003_alter_artist_upload_alter_playlist_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='upload',
            field=models.ImageField(upload_to='media/artists/%c'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='upload',
            field=models.ImageField(blank=True, upload_to='media/playlists/<django.db.models.query_utils.DeferredAttribute object at 0x0000022F92BFB3A0>/% Y/% m/% d/'),
        ),
    ]
