# Generated by Django 4.0 on 2022-08-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audify', '0006_alter_playlist_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='upload',
            field=models.ImageField(upload_to='artists/%c/'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='upload',
            field=models.ImageField(blank=True, upload_to='media/playlists/<django.db.models.query_utils.DeferredAttribute object at 0x000001813D55B3A0>/% Y/% m/% d/'),
        ),
    ]
