# Generated by Django 4.0 on 2022-08-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audify', '0009_alter_artist_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='file',
            field=models.FileField(default='', upload_to='songs/<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.CharField>'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='upload',
            field=models.ImageField(upload_to='albums'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='upload',
            field=models.ImageField(upload_to='artists/<django.db.models.fields.CharField>'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='upload',
            field=models.ImageField(blank=True, upload_to='playlists'),
        ),
    ]
