# Generated by Django 4.0 on 2022-08-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audify', '0010_song_file_alter_album_upload_alter_artist_upload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='upload',
            field=models.ImageField(upload_to='artists'),
        ),
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(upload_to='songs'),
        ),
    ]
